# Generated by Django 5.0 on 2023-12-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.TextField(max_length=30)),
                ('jobDescription', models.CharField(max_length=500)),
                ('companyName', models.CharField(max_length=30)),
                ('jobPosition', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
                ('postExpireDate', models.DateField()),
            ],
        ),
    ]
